name: 'CI'
on: 
  [workflow_dispatch,push, pull_request]

jobs:
 FirstJob: 
    runs-on: ubuntu-latest
    env:
      net_version: '10.0.x'
    steps:
     - name: Checkout Repo 
       uses: actions/checkout@v7

     - name: Restoring, building and testing! 😭
       uses: actions/setup-dotnet@v6
       with:
         dotnet-version: $net_version
     - name: Running tests
       run: |
         echo "Starting installation of $net_version"
         echo "Starting restore!"
         dotnet restore
         echo "Starting build!"
         dotnet build --no-restore --configuration Release
         echo "Trying tests!"
         dotnet test --no-build --configuration Release


          
        
  
  
